FROM python:3.8-slim
RUN mkdir -p /app/
RUN mkdir -p /lib3/
COPY sktime-0.7.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl /lib3/sktime-0.7.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
COPY ./* /app/
WORKDIR /app
RUN python -m pip install -r requirements.txt
ENV PATH /usr/bin/python:$PATH
EXPOSE 8888
# RUN chmod u+x *.sh
CMD ['/bin/bash','run.sh']